SDK_NAME = "Titan SDK"

DEFAULT_TIMEOUT = 10
DEFAULT_HEARTBEAT_INTERVAL = 60
DEFAULT_QUEUE_FLUSH_INTERVAL = 5

DEFAULT_RETRY_BASE_DELAY = 5
DEFAULT_RETRY_MAX_DELAY = 60
DEFAULT_RETRY_MAX_ATTEMPTS = 10
